package com.myspace.jbpm_bpm_loja_online;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Checkout implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nome do Destinatário")
	private java.lang.String receiptName;
	@org.kie.api.definition.type.Label("Endereço Destino")
	private java.lang.String address;

	@org.kie.api.definition.type.Label("Lista de Produtos")
	private java.util.List<com.myspace.jbpm_bpm_loja_online.Product> productList;

	@org.kie.api.definition.type.Label(value = "Pedido FInalizado")
	private java.lang.Boolean isFinalized;

	@org.kie.api.definition.type.Label(value = "Id do Usuário")
	private java.lang.String userid;

	public Checkout() {
	}

	public java.lang.String getReceiptName() {
		return this.receiptName;
	}

	public void setReceiptName(java.lang.String receiptName) {
		this.receiptName = receiptName;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.util.List<com.myspace.jbpm_bpm_loja_online.Product> getProductList() {
		return this.productList;
	}

	public void setProductList(
			java.util.List<com.myspace.jbpm_bpm_loja_online.Product> productList) {
		this.productList = productList;
	}

	public java.lang.Boolean getIsFinalized() {
		return this.isFinalized;
	}

	public void setIsFinalized(java.lang.Boolean isFinalized) {
		this.isFinalized = isFinalized;
	}

	public java.lang.String getUserid() {
		return this.userid;
	}

	public void setUserid(java.lang.String userid) {
		this.userid = userid;
	}

	public Checkout(
			java.lang.String receiptName,
			java.lang.String address,
			java.util.List<com.myspace.jbpm_bpm_loja_online.Product> productList,
			java.lang.Boolean isFinalized, java.lang.String userid) {
		this.receiptName = receiptName;
		this.address = address;
		this.productList = productList;
		this.isFinalized = isFinalized;
		this.userid = userid;
	}

}